### ISSUE TITLE
Missing Tailwind Standart

### ISSUE THREAD

**Issue by feliciofilipe** [cesium/guides#1]
I suggest this one: https://github.com/heybourn/headwind

**Comment by nelsonmestevao** [comment]
We could recommend that plugin for VS Code, but we should always be based on tools that integrate well with our git flow. I found this https://github.com/avencera/rustywind cli that does the same as headwind. It can be integrated with any editor, and we can use it on our CI/CD pipelines.

**Comment by feliciofilipe** [comment]
Looks very nice!

**Comment by nelsonmestevao** [comment]
No more discussions needed: https://tailwindcss.com/blog/automatic-class-sorting-with-prettier :rocket:
